name: Test Module

on:
  pull_request:
    paths:
      - '*.tf'
      - 'tests/**'
      - 'examples/postgresql-test/**'
      - '.github/workflows/terraform-test.yml'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  id-token: write
  
jobs:
  test:
    name: Run Terraform Tests
    uses: oozou/cicd/.github/workflows/terraform-test.yml@master
    secrets: inherit
    with:
      aws_region: 'ap-southeast-1'
      tf_version: '1.6.0'
      go_version: '1.21'
      test_example_path: 'examples/postgresql-test'
      timeout_minutes: 60
      module_name: 'AWS Aurora'
      iam_oidc_role: 'arn:aws:iam::562563527952:role/oozou-internal-devops-github-action-oidc-role' # oozou internal account
